from __future__ import annotations

from enum import Enum


class ActionType(str, Enum):
    NORMAL_SUMMON = "NORMAL_SUMMON"
    FLIP_SUMMON = "FLIP_SUMMON"
    SPECIAL_SUMMON = "SPECIAL_SUMMON"
    SET_MONSTER = "SET_MONSTER"
    ACTIVATE_SPELL = "ACTIVATE_SPELL"
    ACTIVATE_TRAP = "ACTIVATE_TRAP"
    DECLARE_ATTACK = "DECLARE_ATTACK"
    PASS_PRIORITY = "PASS_PRIORITY"
    DRAW_PHASE = "DRAW_PHASE"
    STANDBY_PHASE = "STANDBY_PHASE"
    MAIN_PHASE_1 = "MAIN_PHASE_1"
    BATTLE_PHASE = "BATTLE_PHASE"
    MAIN_PHASE_2 = "MAIN_PHASE_2"
    END_PHASE = "END_PHASE"
