from enum import Enum


class PHASE(Enum):
    DRAW = "抽卡阶段"
    STANDBY = "准备阶段"
    MAIN1 = "主要阶段1"

    BATTLE = "战斗阶段"
    BATTLE_START = "战斗开始"
    BATTLE_STEP = "战斗步骤"
    BATTLE_DAMAGE = "伤害步骤"
    BATTLE_DAMAGE_CALCULATION = "伤害计算时"
    BATTLE_END = "战斗阶段结束"

    MAIN2 = "主要阶段2"
    END = "结束阶段"


CONSEQUENCE_OF_TURN_1 = {
    PHASE.DRAW: [PHASE.STANDBY],
    PHASE.STANDBY: [PHASE.MAIN1],
    PHASE.MAIN1: [PHASE.END],
    PHASE.END: [PHASE.DRAW],
}
CONSEQUENCE = CONSEQUENCE_OF_TURN_1 | {
    PHASE.MAIN1: [PHASE.BATTLE, PHASE.END],
    PHASE.BATTLE: [PHASE.BATTLE_START, PHASE.MAIN2, PHASE.END],
    PHASE.BATTLE_START: [PHASE.BATTLE_STEP],
    PHASE.BATTLE_STEP: [PHASE.BATTLE_DAMAGE],
    PHASE.BATTLE_DAMAGE: [PHASE.BATTLE_DAMAGE_CALCULATION],
    PHASE.BATTLE_DAMAGE_CALCULATION: [PHASE.BATTLE_END],
    PHASE.BATTLE_END: [PHASE.BATTLE],
    PHASE.MAIN2: [PHASE.END],
}
